package gent.zeus.guitar

/**
 * error generated by the application that can be returned to the user
 */
abstract class DataFetchError(val message: String, val httpStatusCode: Int) {

    override fun toString(): String {
        return this::class.simpleName ?: "anonymous class"
    }
}

/**
 * error caused by user wrongdoing
 */
open class UserError(message: String, httpStatusCode: Int = 500) : DataFetchError(message, httpStatusCode)

/**
 * error caused by server mishaps
 */
open class ServerError(message: String, httpStatusCode: Int = 400) : DataFetchError(message, httpStatusCode)

sealed class DataResult<T> {
    data class DataSuccess<T>(val value: T) : DataResult<T>()
    data class DataError<E : DataFetchError, T>(val error: E) : DataResult<T>()
}

data class DoubleErrorLists(
    val important: List<DataFetchError>,
    val unimportant: List<DataFetchError>,
)

/**
 * log all the errors in the list
 * @param pre: bit to put before the error message
 */
fun <E : DataFetchError> Iterable<E>.logErrors(pre: String) = map {
    Logging.log.error("$pre ${it.message} (${it.httpStatusCode})")
    it
}
