package gent.zeus.guitar

/**
 * error generated by the application that can be returned to the user
 *
 * @param message message of the error
 * @param remoteError error from the remote that caused this error
 */
abstract class DataFetchError(val message: String, val remoteError: String?, val httpStatusCode: Int) {

    override fun toString(): String {
        return this::class.simpleName ?: "anonymous class"
    }
}

/**
 * error caused by user wrongdoing
 */
open class UserError(message: String, remoteError: String?, httpStatusCode: Int = 400) :
    DataFetchError(message, remoteError, httpStatusCode)

/**
 * error caused by server mishaps
 */
open class ServerError(message: String, remoteError: String?, httpStatusCode: Int = 500) :
    DataFetchError(message, remoteError, httpStatusCode)

class MultiError(errors: List<DataFetchError>) : DataFetchError(
    message = errors.joinToString(
        ", ",
        if (errors.size > 1) "multiple errors were encountered: " else "",
    ) { "${it.message} (${it.httpStatusCode})" },
    remoteError = errors.joinToString(
        "; ",
    ) { "${it.remoteError}" },
    httpStatusCode = when {
        errors.any { it is UserError && it.httpStatusCode == 404 } -> 404
        errors.any { it is UserError } -> 400
        else -> 500
    }
)

/**
 * success or error when handling musical data
 */
sealed class DataResult<out T> {
    data class Ok<T>(val value: T) : DataResult<T>()
    data class Error<E : DataFetchError>(val error: E) : DataResult<Nothing>()
}

/**
 * log all the errors in the list
 * @param pre: bit to put before the error message
 */
fun <E : DataFetchError> Iterable<E>.logErrors(pre: String) = onEach {
    logger.error("$pre ${it.message} (${it.httpStatusCode})")
}

/**
 * tries to execute the code block. if the code throws an exception, it makes an error log statement
 * and re-throws the exception
 *
 * @param messageOnFail message to put in log statement (will append ` (stacktrace below)`)
 * @param block code block to try executing
 */
fun logException(messageOnFail: String, block: () -> Unit) {
    try {
        block()
    } catch (e: Exception) {
        logger.error("$messageOnFail (stacktrace below)")
        throw e
    }
}
