package gent.zeus.guitar.ext

import gent.zeus.guitar.DataResult
import gent.zeus.guitar.data.MusicModel

/**
 * data filler that tries to use the main filler, and if it fails, uses the backup filler
 *
 * if the backup filler fails, it returns the error generated by that
 */
class CombinedModelFiller<T : MusicModel>(
    val mainFiller: ModelFiller<T>,
    val fallbackFiller: ModelFiller<T>
) : ModelFiller<T> {
    override fun fetchInto(musicModel: T): DataResult<T> =
        when (val it = mainFiller.fetchInto(musicModel)) {
            is DataResult.Ok -> it
            is DataResult.Error<*> -> fallbackFiller.fetchInto(musicModel)
        }
}

@Suppress("unused")
infix fun <T : MusicModel> ModelFiller<T>.or(other: ModelFiller<T>) =
    CombinedModelFiller(this, other)

