package gent.zeus.guitar.ext

import gent.zeus.guitar.DataResult
import gent.zeus.guitar.data.MusicalObject

/**
 * data filler that tries to use the main filler, and if it fails, uses the backup filler
 *
 * if the backup filler fails, it returns the error generated by that
 */
class CombinedDataFiller<T : MusicalObject>(
    val mainFiller: DataFiller<T>,
    val fallbackFiller: DataFiller<T>
) : DataFiller<T> {
    override fun fetchInto(musicalObject: T): DataResult<T> =
        when (val it = mainFiller.fetchInto(musicalObject)) {
            is DataResult.DataSuccess<*> -> it
            is DataResult.DataError<*, *> -> fallbackFiller.fetchInto(musicalObject)
        }
}
